### ISSUE TITLE
Should I use libc++ or libstdc++?

### ISSUE THREAD

**Issue by KevinJue** [Insiteo/ios-v3#2]
Hi, 

When i merged insiteo project with mine, some error (91) occured on compilation because of libc++.
I fixed it by used libstdc++ 

libc++ is not 100% complete on GNU/Linux, and there's no real advantage to using it when libstdc++ is more complete. Also, if you want to link to any other libraries written in C++ they will almost certainly have been built with libstdc++ so you'll need to link with that too to use them.

**Comment by bleguelvouit** [comment]
Hi,
In our Getting Started we recommend to use the "Compiler default" option.
Did you set this option manually to "libc++" in your project for a specific reason?

**Comment by KevinJue** [comment]
sure i did. 

C++ Standard Library is set to Compiler Default, but i can't run app with libc++, currently it's fixed by using libstdc++ so i think it will be okay

**Comment by bleguelvouit** [comment]
We used to recommend the "libstdc++" option in the past (you can find this advice in the 3.1.1) but we recently managed to make it run with the "Compiler Default" option.

For example the sampleapp project uses this option.

I think it's much more a cross libraries dependencies issue that can easily be fixed with your solution.

Thanks to share it with us.
